import type { NetizenManifest } from "@netizen-labs/protocol";

/**
 * The PURE core of `netizen render`: manifest → an inspectable bundle
 * (config files + an ordered plan). No I/O, no infra, deterministic — this is
 * what we TDD. Secrets are emitted only as references, never resolved.
 * See docs/superpowers/specs/2026-07-26-netizen-node-installer.md.
 */

export interface Step {
  id: string;
  phase: string;
  title: string;
}

export interface Bundle {
  /** relative path → file contents */
  files: Record<string, string>;
  plan: Step[];
  /** every $REF / vault: the operator must supply before `up` */
  secretRefs: string[];
}

/** Does this node's stack need a database? (Matrix, Nextcloud, XWiki, OpenProject) */
export function composeNeedsPostgres(m: NetizenManifest): boolean {
  const ws = m.services.workspace;
  return !!(m.services.chat?.matrix || ws?.nextcloud || ws?.wiki || ws?.project || ws?.mail);
}

const rp = (m: NetizenManifest, id: string) =>
  m.identity.relyingParties.find((r) => r.id === id);

const header = (m: NetizenManifest, what: string) =>
  `# Generated by \`netizen render\` — ${what} for node "${m.id}"\n`;

/** Best-effort hostname from an http(s) or wss url. */
function hostname(u: string): string {
  try {
    return new URL(u).hostname;
  } catch {
    return u.replace(/^[a-z]+:\/\//, "").replace(/\/.*$/, "");
  }
}

export function renderRoebelIdEnv(m: NetizenManifest): string {
  const nc = rp(m, "nextcloud");
  const mx = rp(m, "matrix");
  const s = m.services.secrets ?? {};
  const lines = [
    header(m, "Röbel ID keystone env").trimEnd(),
    `ISSUER_URL=${m.identity.idp.issuer}`,
    `CHAIN_ID=${m.chain.chainId}`,
    `GNOSIS_RPC_URL=${m.chain.rpc}`,
    `CITIZEN_NFT_ADDRESS=${m.contracts.citizenNft}`,
    `ATTESTER_NFT_ADDRESS=${m.contracts.attesterNft}`,
    `THIRDWEB_CLIENT_ID=$THIRDWEB_CLIENT_ID`,
    `JWKS_JSON=${m.identity.idp.jwks}`,
  ];
  if (nc) {
    lines.push(
      `NEXTCLOUD_CLIENT_ID=${nc.id}`,
      `NEXTCLOUD_CLIENT_SECRET=${s.nextcloudClientSecret ?? "$NEXTCLOUD_CLIENT_SECRET"}`,
      `NEXTCLOUD_REDIRECT_URIS=${nc.redirectUris.join(",")}`,
    );
  }
  if (mx) {
    lines.push(
      `MATRIX_CLIENT_ID=${mx.id}`,
      `MATRIX_CLIENT_SECRET=${s.matrixClientSecret ?? "$MATRIX_CLIENT_SECRET"}`,
      `MATRIX_REDIRECT_URIS=${mx.redirectUris.join(",")}`,
    );
  }
  return lines.join("\n") + "\n";
}

/**
 * App env — one line per workspace surface the node declares. Each var lights up
 * exactly one dashboard tile (citizen + org), so a node ships with the subset it runs.
 */
export function renderWebEnv(m: NetizenManifest): string {
  const ws = m.services.workspace;
  const pairs: Array<[string, string | undefined]> = [
    ["NEXT_PUBLIC_WORKSPACE_BASE_URL", ws?.nextcloud],
    ["NEXT_PUBLIC_CHAT_BASE_URL", m.services.chat?.matrix?.element],
    ["NEXT_PUBLIC_MAIL_BASE_URL", ws?.mail],
    ["NEXT_PUBLIC_WIKI_BASE_URL", ws?.wiki],
    ["NEXT_PUBLIC_VIDEO_BASE_URL", ws?.video],
    ["NEXT_PUBLIC_PROJECT_BASE_URL", ws?.project],
    ["NEXT_PUBLIC_AGENTS_BASE_URL", ws?.portal],
  ];
  const lines = [header(m, "web app env").trimEnd()];
  for (const [key, value] of pairs) if (value) lines.push(`${key}=${value}`);
  return lines.join("\n") + "\n";
}

export function renderElementConfig(m: NetizenManifest): string {
  const hs = m.services.chat?.matrix?.homeserver ?? "";
  return (
    JSON.stringify(
      { default_server_config: { "m.homeserver": { base_url: hs } }, default_country_code: "DE" },
      null,
      2,
    ) + "\n"
  );
}

export function renderMasConfig(m: NetizenManifest): string {
  const mx = rp(m, "matrix");
  const secret = m.services.secrets?.matrixClientSecret ?? "$MATRIX_CLIENT_SECRET";
  const callback = mx?.redirectUris[0] ?? "";
  const ulid = callback.split("/").pop() || "01ROEBELIDPROVIDERULID000000";
  return `${header(m, "MAS upstream OIDC = the node's Röbel ID")}upstream_oauth2:
  providers:
    - id: ${ulid}
      issuer: ${m.identity.idp.issuer}
      human_name: "${m.name} ID"
      client_id: "${mx?.id ?? "matrix"}"
      client_secret: "${secret}"
      scope: "${m.identity.idp.scopes.join(" ")}"
      token_endpoint_auth_method: client_secret_basic
      claims_imports:
        subject: { template: "{{ user.sub }}" }
        localpart: { template: "{{ user.sub }}" }
        displayname: { template: "{{ user.name }}" }
        email: { template: "{{ user.email }}" }
`;
}

export function renderNextcloudSetup(m: NetizenManifest): string {
  const nc = rp(m, "nextcloud");
  const secret = m.services.secrets?.nextcloudClientSecret ?? "$NEXTCLOUD_CLIENT_SECRET";
  return `#!/usr/bin/env bash
${header(m, "Nextcloud OIDC + group folders (run inside the container)")}set -euo pipefail
php occ app:install user_oidc || true
php occ user_oidc:provider "${m.name}" \\
  --clientid="${nc?.id ?? "nextcloud"}" \\
  --clientsecret="${secret}" \\
  --discoveryuri="${m.identity.idp.discovery}" \\
  --scope="${m.identity.idp.scopes.join(" ")}" \\
  --unique-uid=1 --mapping-uid=sub --mapping-email=email \\
  --mapping-display-name=name --mapping-groups=groups
php occ config:app:set user_oidc provisioning_groups --value=1
php occ app:install groupfolders || true
# One group folder per org (ACL = org:<accountId>:<role>) is provisioned by
# \`netizen up\` from the org registry — idempotent (create-if-absent).
`;
}

export function renderStrfryConf(m: NetizenManifest): string {
  const host = hostname(m.services.chat?.nostr?.relay ?? "");
  return `${header(m, "Nostr relay (strfry)")}db = "/app/strfry-db/"
relay {
  bind = "0.0.0.0"
  port = 7777
  info {
    name = "${m.name} Relay"
    description = "Sovereign community relay for ${m.name}${host ? ` (${host})` : ""}"
  }
  writePolicy { plugin = "/etc/strfry/write-policy.sh" }   # members-only writes (reads open)
}
`;
}

/** Caddy reverse proxy for every service subdomain the manifest declares (auto TLS). */
export function renderCaddyfile(m: NetizenManifest): string {
  const blocks: string[] = [];
  const add = (u: string | undefined, upstream: string) => {
    if (u) blocks.push(`${hostname(u)} {\n  reverse_proxy ${upstream}\n}`);
  };
  // Only route the IdP locally when this node actually hosts it. An externally
  // hosted keystone (e.g. on Fly) resolves via its own DNS/TLS — routing it here
  // would blackhole logins for every service on the node.
  if (m.identity.idp.hosted !== "external") add(m.identity.idp.issuer, "roebel-id:3010");
  const ws = m.services.workspace;
  if (ws?.nextcloud && ws.collabora) {
    // Collabora shares the Nextcloud host: its own paths go to the editor, the
    // rest to Nextcloud. Same-origin keeps WOPI simple and needs no extra DNS
    // record or certificate. (Without this the Office app 404s — the editor is
    // running but unreachable.)
    // `handle` blocks are mutually exclusive and evaluated in written order.
    // Two bare `reverse_proxy` directives do NOT preserve order in Caddy — the
    // Collabora paths silently fell through to Nextcloud and Office 404'd.
    blocks.push(`${hostname(ws.nextcloud)} {
  handle /browser/* {
    reverse_proxy collabora:9980
  }
  handle /hosting/* {
    reverse_proxy collabora:9980
  }
  handle /cool/* {
    reverse_proxy collabora:9980
  }
  handle {
    reverse_proxy nextcloud:80
  }
}`);
  } else {
    add(ws?.nextcloud, "nextcloud:80");
  }
  add(ws?.mail, "ox:8080"); // Open-Xchange
  add(ws?.wiki, "xwiki:8080");
  add(ws?.video, "jitsi:8000");
  add(ws?.project, "openproject:80");
  // NOTE: `portal` is a link target for the agent-workspace tile, not a service
  // this installer provisions yet — no Caddy route until something backs it.
  add(m.services.chat?.matrix?.homeserver, "synapse:8008");
  add(m.services.chat?.matrix?.mas, "mas:8080");
  add(m.services.chat?.matrix?.element, "element:80");
  const relay = m.services.chat?.nostr?.relay;
  if (relay) blocks.push(`${hostname(relay)} {\n  reverse_proxy strfry:7777\n}`);
  return header(m, "Caddy reverse proxy (auto TLS)") + "\n" + blocks.join("\n\n") + "\n";
}

/** The deployable stack — every service this node declares, and nothing else. */
export function renderComposeYml(m: NetizenManifest): string {
  const hasMatrix = !!m.services.chat?.matrix;
  const hasNostr = !!m.services.chat?.nostr;
  // An externally hosted keystone (identity.idp.hosted === "external") is NOT
  // provisioned here: starting a second one would shadow the real issuer.
  const hostsIdp = m.identity.idp.hosted !== "external";
  const svc: string[] = [
    `  caddy:
    image: caddy:2
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes: ["./Caddyfile:/etc/caddy/Caddyfile", "caddy_data:/data"]`,
  ];
  if (hostsIdp) {
    svc.push(`  roebel-id:
    image: \${ROEBEL_ID_IMAGE:-ghcr.io/roebel-labs/roebel-id:latest}
    restart: unless-stopped
    env_file: ["./roebel-id.env"]
    expose: ["3010"]`);
  }
  if (hasMatrix) {
    svc.push(
      `  postgres:
    image: postgres:16
    restart: unless-stopped
    environment: { POSTGRES_PASSWORD: "\${POSTGRES_PASSWORD}" }
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - "./postgres/init:/docker-entrypoint-initdb.d:ro"`,
      `  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    volumes: ["./synapse:/data"]
    depends_on: [postgres, mas]
    expose: ["8008"]`,
      `  mas:
    image: ghcr.io/element-hq/matrix-authentication-service:latest
    restart: unless-stopped
    command: server
    volumes: ["./mas/config.yaml:/config.yaml"]
    depends_on: [postgres]
    expose: ["8080"]`,
      `  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
    volumes: ["./element/config.json:/app/config.json"]
    expose: ["80"]`,
    );
  }
  if (hasNostr) {
    // The relay mounts the POLICY DIRECTORY (not single files): editors/sed -i
    // replace inodes, and a single-file bind mount would keep the stale inode,
    // so live grants/revokes of the write allow-list would silently not apply.
    svc.push(
      `  strfry:
    image: ghcr.io/hoytech/strfry:latest
    restart: unless-stopped
    command: relay
    volumes:
      - "./strfry.conf:/etc/strfry.conf"
      - "./strfry-policy:/etc/strfry:ro"
      - "strfry_db:/app/strfry-db"
    expose: ["7777"]`,
    );
  }

  // ---- Workspace (the openDesk-equivalent suite). Each is provisioned only
  // when the manifest declares its URL, so every node picks its own subset.
  const ws = m.services.workspace;
  if (ws?.nextcloud) {
    svc.push(
      `  nextcloud:
    image: nextcloud:stable
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: "\${POSTGRES_PASSWORD}"
      NEXTCLOUD_TRUSTED_DOMAINS: "${hostname(ws.nextcloud)}"
      OVERWRITEPROTOCOL: https
    volumes: ["nextcloud_data:/var/www/html"]
    depends_on: [postgres]
    expose: ["80"]`,
    );
    if (ws.collabora) {
      svc.push(
        `  collabora:
    image: collabora/code:latest
    restart: unless-stopped
    environment:
      aliasgroup1: "https://${hostname(ws.nextcloud)}"
      DONT_GEN_SSL_CERT: "true"
      extra_params: "--o:ssl.enable=false --o:ssl.termination=true"
    expose: ["9980"]`,
      );
    }
  }
  if (ws?.mail) {
    svc.push(
      `  ox:                      # Open-Xchange (mail/calendar/contacts)
    image: \${OX_IMAGE:-openexchange/appsuite:latest}
    restart: unless-stopped
    depends_on: [postgres]
    expose: ["8080"]
    # NOTE: OX needs an IMAP/SMTP backend + its own provisioning — see PLAN.md`,
    );
  }
  if (ws?.wiki) {
    svc.push(
      `  xwiki:
    image: xwiki:stable-postgres-tomcat
    restart: unless-stopped
    environment:
      DB_USER: xwiki
      DB_PASSWORD: "\${POSTGRES_PASSWORD}"
      DB_HOST: postgres
    volumes: ["xwiki_data:/usr/local/xwiki"]
    depends_on: [postgres]
    expose: ["8080"]`,
    );
  }
  if (ws?.video) {
    svc.push(
      `  jitsi:                   # single-container Jitsi Meet (web + prosody + jicofo + jvb)
    image: jitsi/web:stable
    restart: unless-stopped
    environment:
      PUBLIC_URL: "${ws.video}"
      ENABLE_AUTH: "1"
      AUTH_TYPE: jwt          # tokens minted from the Röbel ID session
    expose: ["80"]
    # NOTE: full Jitsi needs prosody/jicofo/jvb sidecars + UDP 10000 — see PLAN.md`,
    );
  }
  if (ws?.project) {
    svc.push(
      `  openproject:
    image: openproject/openproject:14
    restart: unless-stopped
    environment:
      OPENPROJECT_HOST__NAME: "${hostname(ws.project)}"
      OPENPROJECT_HTTPS: "true"
      DATABASE_URL: "postgres://openproject:\${POSTGRES_PASSWORD}@postgres/openproject"
    volumes: ["openproject_data:/var/openproject/assets"]
    depends_on: [postgres]
    expose: ["80"]`,
    );
  }

  // ---- Sovereign AI gateway (model routing; keeps egress under node policy).
  if (m.ai?.selfHosted) {
    svc.push(
      `  litellm:                 # AI gateway — routes models, enforces data-egress policy
    image: ghcr.io/berriai/litellm:main-latest
    restart: unless-stopped
    env_file: ["./.env"]
    volumes: ["./ai/litellm.yaml:/app/config.yaml"]
    command: ["--config", "/app/config.yaml"]
    expose: ["4000"]`,
    );
  }

  // Postgres backs Matrix, Nextcloud, XWiki and OpenProject — include it if any need it.
  const needsPostgres =
    hasMatrix || !!ws?.nextcloud || !!ws?.wiki || !!ws?.project || !!ws?.mail;
  // (hasMatrix already emitted postgres above; append it here for the other cases.
  // Order within `services:` is irrelevant to compose — depends_on drives startup.)
  if (needsPostgres && !hasMatrix) {
    svc.push(`  postgres:
    image: postgres:16
    restart: unless-stopped
    environment: { POSTGRES_PASSWORD: "\${POSTGRES_PASSWORD}" }
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - "./postgres/init:/docker-entrypoint-initdb.d:ro"`);
  }

  const vols = ["caddy_data:"];
  if (needsPostgres) vols.push("pg_data:");
  if (hasNostr) vols.push("strfry_db:");
  if (ws?.nextcloud) vols.push("nextcloud_data:");
  if (ws?.wiki) vols.push("xwiki_data:");
  if (ws?.project) vols.push("openproject_data:");

  return `# Generated by \`netizen render\` — the sovereign node stack for "${m.id}".
# One command brings up everything this node declares: identity, comms, workspace,
# and AI. Services appear only when the manifest declares them.
# Secrets come from ./.env (see SECRETS.md) — never from this file.
services:
${svc.join("\n")}
volumes:
${vols.map((v) => `  ${v}`).join("\n")}
`;
}

/**
 * The Nostr write policy — CitizenNFT-gated. Rendered by the installer so every
 * node gets the same members-only relay without hand-wiring it (reads stay open).
 * Mirrors packages/cli/policies/nostr-citizen-write/.
 */
export function renderNostrPolicyAwk(m: NetizenManifest): string {
  return `# Generated by \`netizen render\` — write policy for node "${m.id}".
# Accept an EVENT only if its author pubkey is in the members allow-list.
# Re-reads the list per event (live grants/revokes) and fflush()es so strfry
# never blocks on a buffered pipe. Reads are unaffected.
{
  line = $0
  if (!match(line, /"id":"[0-9a-fA-F]{64}"/)) next
  id = substr(line, RSTART + 6, 64)
  pk = ""
  if (match(line, /"pubkey":"[0-9a-fA-F]{64}"/)) pk = tolower(substr(line, RSTART + 10, 64))
  allowed = 0
  if (pk != "") {
    while ((getline p < "/etc/strfry/members.txt") > 0) {
      gsub(/[ \\t\\r\\n]/, "", p)
      if (p != "" && substr(p, 1, 1) != "#" && tolower(p) == pk) { allowed = 1; break }
    }
    close("/etc/strfry/members.txt")
  }
  if (allowed)
    printf("{\\"id\\":\\"%s\\",\\"action\\":\\"accept\\"}\\n", id)
  else
    printf("{\\"id\\":\\"%s\\",\\"action\\":\\"reject\\",\\"msg\\":\\"blocked: only ${m.name} members may publish to this relay\\"}\\n", id)
  fflush()
}
`;
}

export function renderNostrPolicyWrapper(): string {
  return `#!/bin/sh\nexec awk -f /etc/strfry/policy.awk\n`;
}

export function renderNostrMembers(m: NetizenManifest): string {
  const cred = m.identity.membership.credential;
  return `# ${m.name} — Nostr write allow-list. One lowercase 64-hex pubkey per line.
# Populated from ${cred} holders: derive each member's Nostr key from their wallet
# (NIP-06 style, Schnorr != ECDSA so it is a DERIVED key), verify they hold the
# credential on chain, then add the pubkey here. Reads are always open.
# Grant: add-member.sh <pubkey>   Revoke: delete the line. Both take effect live.
`;
}

export function renderNostrAddMember(): string {
  return `#!/bin/sh
# Usage: add-member.sh <64-hex-nostr-pubkey>  — grant write access (live, no restart)
pk="$1"
echo "$pk" | grep -qiE '^[0-9a-f]{64}$' || { echo "not a 64-hex nostr pubkey: $pk" >&2; exit 1; }
f="$(dirname "$0")/members.txt"
grep -qi "^\${pk}$" "$f" 2>/dev/null || printf '%s\\n' "$pk" >> "$f"
echo "granted write: $pk"
`;
}

/**
 * Postgres bootstrap. The image only creates the default superuser; every service
 * that shares this database (Nextcloud, Synapse, XWiki, OpenProject) needs its OWN
 * role and database, or it fails with "password authentication failed for user X".
 * Runs once, on first initialisation of an empty data directory.
 */
export function renderPostgresInit(m: NetizenManifest): string {
  const ws = m.services.workspace;
  const dbs: string[] = [];
  if (ws?.nextcloud) dbs.push("nextcloud");
  if (m.services.chat?.matrix) dbs.push("synapse", "mas");
  if (ws?.wiki) dbs.push("xwiki");
  if (ws?.project) dbs.push("openproject");
  const body = dbs
    .map(
      (d) => `CREATE ROLE ${d} LOGIN PASSWORD '\${POSTGRES_PASSWORD}';
CREATE DATABASE ${d} OWNER ${d}${d === "synapse" ? " ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' TEMPLATE template0" : ""};`,
    )
    .join("\n");
  return `#!/bin/bash
# Generated by \`netizen render\` — per-service roles + databases for node "${m.id}".
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
${body || "SELECT 1;"}
EOSQL
`;
}

/** LiteLLM gateway config — model routing + the node's data-egress posture. */
export function renderLiteLlmConfig(m: NetizenManifest): string {
  const models = Object.entries(m.ai?.models ?? {})
    .map(([role, model]) => `  - model_name: ${role}\n    litellm_params:\n      model: ${model}`)
    .join("\n");
  const tier = m.ai?.sovereignty?.tier ?? "unset";
  const policy = m.ai?.sovereignty?.dataEgressPolicy ?? "unset";
  return `# Generated by \`netizen render\` — AI gateway for node "${m.id}".
# Sovereignty tier: ${tier} · data-egress policy: ${policy}
# API keys come from ./.env (never this file).
model_list:
${models || "  []"}
`;
}

export function renderBundleReadme(m: NetizenManifest): string {
  return `# ${m.name} — Netizen node bundle

Generated by \`netizen render\` from a Netizen Node Manifest. This is the sovereign
node for **${m.name}** (id: \`${m.id}\`).

A **full sovereign stack** — identity, communication, workspace, money rails and AI —
on infrastructure you own. Everything below is generated from one manifest.

## Deploy

1. Provision one box (Ubuntu + Docker) and point DNS at it for every subdomain in
   \`Caddyfile\`.
2. Put a \`.env\` next to this file with every reference listed in \`SECRETS.md\`
   (secrets are referenced, never written into the bundle).
3. \`sudo bash bootstrap.sh\` — or \`netizen up <manifest> --host user@box\` from your
   machine. Brings up the whole declared stack behind Caddy with auto-TLS.
4. Run the post-config steps in \`PLAN.md\` (each service's OIDC provider against the
   keystone — they are idempotent and safe to re-run).
5. Set \`web.env\` on the app host and redeploy so the dashboard tiles light up.

Follow \`PLAN.md\` for the exact ordered, idempotent steps.

## What this node runs

Only what the manifest declares. Every service authenticates against **your own**
identity keystone, so one wallet-based sign-in spans all of them — and the same
identity model makes AI agents members alongside people.
`;
}

/** Idempotent on-box apply script. Run by `netizen up` (or by hand). Re-runnable. */
export function renderBootstrap(m: NetizenManifest): string {
  const hasNextcloud = !!m.services.workspace?.nextcloud;
  const nc = hasNextcloud
    ? `
# 4. Nextcloud OIDC provider + group folders (once the container is initialized).
if docker compose ps --services 2>/dev/null | grep -qx nextcloud; then
  docker compose exec -T -u www-data \\
    -e NEXTCLOUD_CLIENT_SECRET="$NEXTCLOUD_CLIENT_SECRET" \\
    nextcloud sh < nextcloud/setup.sh \\
    || echo "note: re-run once Nextcloud finished its first-run install"
fi`
    : "";
  return `#!/usr/bin/env bash
# Generated by \`netizen render\` — idempotent apply for node "${m.id}". Run ON the box (Ubuntu, sudo).
# Safe to re-run: docker compose converges; every step is create-if-absent.
set -euo pipefail
cd "$(dirname "$0")"

# 1. Docker engine + the compose plugin. Checked SEPARATELY: a box can have
# docker without the plugin, and skipping on \`docker\` alone leaves \`docker
# compose\` broken.
if ! command -v docker >/dev/null 2>&1; then
  apt-get update && apt-get -y install docker.io
  systemctl enable --now docker
fi
if ! docker compose version >/dev/null 2>&1; then
  apt-get update && apt-get -y install docker-compose-plugin \\
    || apt-get -y install docker-compose-v2 \\
    || { echo "ERROR: could not install the docker compose plugin" >&2; exit 1; }
fi

# 2. Secrets — a .env next to this script must supply the refs listed in SECRETS.md.
if [ ! -f .env ]; then
  echo "ERROR: create .env from SECRETS.md (POSTGRES_PASSWORD, ROEBEL_ID_JWKS, ...) before applying." >&2
  echo "Tip: for a secret-free first light, run just the Nostr relay: docker compose up -d strfry" >&2
  exit 1
fi
set -a; . ./.env; set +a

# 3. Bring up the stack (idempotent).
docker compose up -d

# 3b. Restart Caddy. Its config is a bind mount, so "compose up -d" writes the new
# file but does NOT restart the container. "caddy reload" inside the container was
# observed to report success while continuing to serve the OLD routes, so restart
# is the only reliable way to apply routing changes (~1s of downtime).
docker compose restart caddy 2>/dev/null || true

${nc}

echo "Applied node \\"${m.id}\\". Verify: docker compose ps"
`;
}

/** Walk the manifest and collect every secret reference ($ENV / vault:), deduped. */
export function collectSecretRefs(m: NetizenManifest): string[] {
  const out = new Set<string>();
  const walk = (v: unknown) => {
    if (typeof v === "string") {
      if (/^\$[A-Z0-9_]+$/.test(v) || v.startsWith("vault:")) out.add(v);
    } else if (Array.isArray(v)) v.forEach(walk);
    else if (v && typeof v === "object") Object.values(v).forEach(walk);
  };
  walk(m);
  return [...out].sort();
}

export function renderSecretsChecklist(m: NetizenManifest): string {
  const refs = collectSecretRefs(m);
  const items = refs.map((r) => `- [ ] \`${r}\``).join("\n");
  return `${header(m, "secrets the operator must supply before \`netizen up\`")}
These are **references** — supply the real values via env / vault at apply time.
They are never written into the bundle.

${items}
`;
}

export function plan(m: NetizenManifest): Step[] {
  const ws = m.services.workspace;
  const hosts = ["id", ...(ws?.nextcloud ? ["cloud"] : []), ...(m.services.chat?.matrix ? ["matrix", "auth", "chat"] : []),
    ...(m.services.chat?.nostr ? ["relay"] : []), ...(ws?.mail ? ["mail"] : []), ...(ws?.wiki ? ["wiki"] : []),
    ...(ws?.video ? ["meet"] : []), ...(ws?.project ? ["project"] : [])];
  const steps: Step[] = [];
  steps.push({ id: "dns", phase: "provision", title: `Point DNS at the box for: ${hosts.join(", ")}` });
  steps.push({ id: "secrets", phase: "provision", title: "Place .env on the box with every ref from SECRETS.md" });
  steps.push({ id: "compose", phase: "services", title: "docker compose up -d — brings up the whole declared stack" });
  steps.push(
    m.identity.idp.hosted === "external"
      ? { id: "identity", phase: "identity", title: `Keystone hosted externally at ${m.identity.idp.issuer} — verify discovery resolves; nothing to deploy here` }
      : { id: "roebel-id", phase: "identity", title: "Keystone live (roebel-id.env) — the single sign-in for every service below" },
  );
  if (rp(m, "nextcloud")) steps.push({ id: "nextcloud-oidc", phase: "workspace", title: "Run nextcloud/setup.sh (OIDC provider + group folder per org)" });
  if (ws?.mail) steps.push({ id: "mail-oidc", phase: "workspace", title: "Point Open-Xchange at the keystone (OIDC) + its IMAP/SMTP backend" });
  if (ws?.wiki) steps.push({ id: "wiki-oidc", phase: "workspace", title: "Enable the XWiki OIDC provider against the keystone" });
  if (ws?.video) steps.push({ id: "video-auth", phase: "workspace", title: "Jitsi JWT auth from the keystone session (+ prosody/jicofo/jvb, UDP 10000)" });
  if (ws?.project) steps.push({ id: "project-oidc", phase: "workspace", title: "Enable the OpenProject OIDC provider against the keystone" });
  if (m.services.chat?.matrix) steps.push({ id: "mas-oidc", phase: "chat", title: "Apply mas/config.yaml (upstream = the keystone) and restart MAS" });
  if (m.services.chat?.nostr) steps.push({ id: "nostr-relay", phase: "chat", title: "Nostr relay up behind Caddy, members-only writes (strfry-policy/)" });
  if (m.ai?.selfHosted) steps.push({ id: "ai-gateway", phase: "ai", title: "AI gateway (LiteLLM) up — model routing + data-egress policy" });
  steps.push({ id: "web-env", phase: "app", title: "Set web.env on the app host and redeploy (lights up the dashboard tiles)" });
  steps.push({ id: "verify", phase: "verify", title: "doctor — discovery reachable, SSO round-trips, tiles light up" });
  return steps;
}

export function renderPlanMd(m: NetizenManifest): string {
  const rows = plan(m)
    .map((s, i) => `${i + 1}. **[${s.phase}]** ${s.title}  \`(${s.id})\``)
    .join("\n");
  return `${header(m, "ordered, idempotent provisioning plan")}\n${rows}\n`;
}

export function renderBundle(m: NetizenManifest): Bundle {
  const files: Record<string, string> = {
    "README.md": renderBundleReadme(m),
    "bootstrap.sh": renderBootstrap(m),
    "docker-compose.yml": renderComposeYml(m),
    "Caddyfile": renderCaddyfile(m),
    // Keystone env only when this node hosts it; an external keystone keeps its
    // own secrets at its host (emitting a stray env file here would mislead).
    ...(m.identity.idp.hosted === "external" ? {} : { "roebel-id.env": renderRoebelIdEnv(m) }),
    "web.env": renderWebEnv(m),
    "PLAN.md": renderPlanMd(m),
    "SECRETS.md": renderSecretsChecklist(m),
  };
  if (m.services.chat?.matrix) {
    files["mas/config.yaml"] = renderMasConfig(m);
    files["element/config.json"] = renderElementConfig(m);
  }
  if (m.services.chat?.nostr) {
    files["strfry.conf"] = renderStrfryConf(m);
    // The members-only write policy, shipped with the node (not hand-wired).
    files["strfry-policy/policy.awk"] = renderNostrPolicyAwk(m);
    files["strfry-policy/write-policy.sh"] = renderNostrPolicyWrapper();
    files["strfry-policy/members.txt"] = renderNostrMembers(m);
    files["strfry-policy/add-member.sh"] = renderNostrAddMember();
  }
  if (m.ai?.selfHosted) {
    files["ai/litellm.yaml"] = renderLiteLlmConfig(m);
  }
  if (composeNeedsPostgres(m)) {
    files["postgres/init/01-databases.sh"] = renderPostgresInit(m);
  }
  if (m.services.workspace?.nextcloud) {
    files["nextcloud/setup.sh"] = renderNextcloudSetup(m);
  }
  return { files, plan: plan(m), secretRefs: collectSecretRefs(m) };
}
