import type { NetizenManifest } from "@netizen-labs/protocol";

/**
 * The PURE core of `netizen render`: manifest → an inspectable bundle
 * (config files + an ordered plan). No I/O, no infra, deterministic — this is
 * what we TDD. Secrets are emitted only as references, never resolved.
 * See docs/superpowers/specs/2026-07-26-netizen-node-installer.md.
 */

export interface Step {
  id: string;
  phase: string;
  title: string;
}

export interface Bundle {
  /** relative path → file contents */
  files: Record<string, string>;
  plan: Step[];
  /** every $REF / vault: the operator must supply before `up` */
  secretRefs: string[];
}

const rp = (m: NetizenManifest, id: string) =>
  m.identity.relyingParties.find((r) => r.id === id);

const header = (m: NetizenManifest, what: string) =>
  `# Generated by \`netizen render\` — ${what} for node "${m.id}"\n`;

export function renderRoebelIdEnv(m: NetizenManifest): string {
  const nc = rp(m, "nextcloud");
  const mx = rp(m, "matrix");
  const s = m.services.secrets ?? {};
  const lines = [
    header(m, "Röbel ID keystone env").trimEnd(),
    `ISSUER_URL=${m.identity.idp.issuer}`,
    `CHAIN_ID=${m.chain.chainId}`,
    `GNOSIS_RPC_URL=${m.chain.rpc}`,
    `CITIZEN_NFT_ADDRESS=${m.contracts.citizenNft}`,
    `ATTESTER_NFT_ADDRESS=${m.contracts.attesterNft}`,
    `THIRDWEB_CLIENT_ID=$THIRDWEB_CLIENT_ID`,
    `JWKS_JSON=${m.identity.idp.jwks}`,
  ];
  if (nc) {
    lines.push(
      `NEXTCLOUD_CLIENT_ID=${nc.id}`,
      `NEXTCLOUD_CLIENT_SECRET=${s.nextcloudClientSecret ?? "$NEXTCLOUD_CLIENT_SECRET"}`,
      `NEXTCLOUD_REDIRECT_URIS=${nc.redirectUris.join(",")}`,
    );
  }
  if (mx) {
    lines.push(
      `MATRIX_CLIENT_ID=${mx.id}`,
      `MATRIX_CLIENT_SECRET=${s.matrixClientSecret ?? "$MATRIX_CLIENT_SECRET"}`,
      `MATRIX_REDIRECT_URIS=${mx.redirectUris.join(",")}`,
    );
  }
  return lines.join("\n") + "\n";
}

export function renderWebEnv(m: NetizenManifest): string {
  const lines = [header(m, "web app env").trimEnd()];
  const ws = m.services.workspace?.nextcloud;
  const el = m.services.chat?.matrix?.element;
  if (ws) lines.push(`NEXT_PUBLIC_WORKSPACE_BASE_URL=${ws}`);
  if (el) lines.push(`NEXT_PUBLIC_CHAT_BASE_URL=${el}`);
  return lines.join("\n") + "\n";
}

export function renderElementConfig(m: NetizenManifest): string {
  const hs = m.services.chat?.matrix?.homeserver ?? "";
  return (
    JSON.stringify(
      { default_server_config: { "m.homeserver": { base_url: hs } }, default_country_code: "DE" },
      null,
      2,
    ) + "\n"
  );
}

export function renderMasConfig(m: NetizenManifest): string {
  const mx = rp(m, "matrix");
  const secret = m.services.secrets?.matrixClientSecret ?? "$MATRIX_CLIENT_SECRET";
  const callback = mx?.redirectUris[0] ?? "";
  const ulid = callback.split("/").pop() || "01ROEBELIDPROVIDERULID000000";
  return `${header(m, "MAS upstream OIDC = the node's Röbel ID")}upstream_oauth2:
  providers:
    - id: ${ulid}
      issuer: ${m.identity.idp.issuer}
      human_name: "${m.name} ID"
      client_id: "${mx?.id ?? "matrix"}"
      client_secret: "${secret}"
      scope: "${m.identity.idp.scopes.join(" ")}"
      token_endpoint_auth_method: client_secret_basic
      claims_imports:
        subject: { template: "{{ user.sub }}" }
        localpart: { template: "{{ user.sub }}" }
        displayname: { template: "{{ user.name }}" }
        email: { template: "{{ user.email }}" }
`;
}

export function renderNextcloudSetup(m: NetizenManifest): string {
  const nc = rp(m, "nextcloud");
  const secret = m.services.secrets?.nextcloudClientSecret ?? "$NEXTCLOUD_CLIENT_SECRET";
  return `#!/usr/bin/env bash
${header(m, "Nextcloud OIDC + group folders (run inside the container)")}set -euo pipefail
php occ app:install user_oidc || true
php occ user_oidc:provider "${m.name}" \\
  --clientid="${nc?.id ?? "nextcloud"}" \\
  --clientsecret="${secret}" \\
  --discoveryuri="${m.identity.idp.discovery}" \\
  --scope="${m.identity.idp.scopes.join(" ")}" \\
  --unique-uid=1 --mapping-uid=sub --mapping-email=email \\
  --mapping-display-name=name --mapping-groups=groups
php occ config:app:set user_oidc provisioning_groups --value=1
php occ app:install groupfolders || true
# One group folder per org (ACL = org:<accountId>:<role>) is provisioned by
# \`netizen up\` from the org registry — idempotent (create-if-absent).
`;
}

/** Walk the manifest and collect every secret reference ($ENV / vault:), deduped. */
export function collectSecretRefs(m: NetizenManifest): string[] {
  const out = new Set<string>();
  const walk = (v: unknown) => {
    if (typeof v === "string") {
      if (/^\$[A-Z0-9_]+$/.test(v) || v.startsWith("vault:")) out.add(v);
    } else if (Array.isArray(v)) v.forEach(walk);
    else if (v && typeof v === "object") Object.values(v).forEach(walk);
  };
  walk(m);
  return [...out].sort();
}

export function renderSecretsChecklist(m: NetizenManifest): string {
  const refs = collectSecretRefs(m);
  const items = refs.map((r) => `- [ ] \`${r}\``).join("\n");
  return `${header(m, "secrets the operator must supply before \`netizen up\`")}
These are **references** — supply the real values via env / vault at apply time.
They are never written into the bundle.

${items}
`;
}

export function plan(m: NetizenManifest): Step[] {
  const steps: Step[] = [];
  steps.push({ id: "dns", phase: "provision", title: `Point DNS for node "${m.id}" at the box (id/cloud/matrix/auth/chat)` });
  steps.push({ id: "compose", phase: "services", title: "docker compose up — Synapse + MAS + Postgres + Element (+ Nextcloud AIO)" });
  steps.push({ id: "roebel-id", phase: "identity", title: "Apply roebel-id.env and deploy the keystone" });
  if (rp(m, "nextcloud")) steps.push({ id: "nextcloud-oidc", phase: "workspace", title: "Run nextcloud/setup.sh (OIDC provider + group folders)" });
  if (rp(m, "matrix")) steps.push({ id: "mas-oidc", phase: "chat", title: "Apply mas/config.yaml (upstream = Röbel ID) and restart MAS" });
  steps.push({ id: "web-env", phase: "app", title: "Set web.env on the app host and redeploy" });
  steps.push({ id: "verify", phase: "verify", title: "doctor — discovery reachable, SSO round-trips, dashboard tiles light up" });
  return steps;
}

export function renderPlanMd(m: NetizenManifest): string {
  const rows = plan(m)
    .map((s, i) => `${i + 1}. **[${s.phase}]** ${s.title}  \`(${s.id})\``)
    .join("\n");
  return `${header(m, "ordered, idempotent provisioning plan")}\n${rows}\n`;
}

export function renderBundle(m: NetizenManifest): Bundle {
  const files: Record<string, string> = {
    "roebel-id.env": renderRoebelIdEnv(m),
    "web.env": renderWebEnv(m),
    "PLAN.md": renderPlanMd(m),
    "SECRETS.md": renderSecretsChecklist(m),
  };
  if (m.services.chat?.matrix) {
    files["mas/config.yaml"] = renderMasConfig(m);
    files["element/config.json"] = renderElementConfig(m);
  }
  if (m.services.workspace?.nextcloud) {
    files["nextcloud/setup.sh"] = renderNextcloudSetup(m);
  }
  return { files, plan: plan(m), secretRefs: collectSecretRefs(m) };
}
